### ISSUE TITLE
VS Code looks for a top-level tsconfig.json

### ISSUE THREAD

**Issue by dystopiandev** [ersenal/pulumi-turborepo-micro-stacks#1]
There should be a top-level tsconfig.json to suppress it

**Comment by ersenal** [comment]
Thanks for the PR. I think the issue you're having is due to how the ESLint plugin computes working directories in VSCode. Adding the following project configuration might help fix it:

```json
{
  "eslint.workingDirectories": [{ "mode": "auto" }]
}
```
